# Generated by Django 6.0.4 on 2026-06-17 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buku', '0001_initial'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Dipinjam', max_length=50)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('buku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buku.buku')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
        ),
    ]
