# Generated by Django 6.0.4 on 2026-06-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='jatuh_tempo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='keperluan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
