# Generated by Django 6.0.4 on 2026-06-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('stok', models.IntegerField(default=0)),
                ('status_buku', models.CharField(default='Aktif', max_length=50)),
            ],
        ),
    ]
